#name: Build Gradle project
#
#on:
#  push:
#  pull_request:
#  release:
#  deployment:
#
#jobs:
#  gradle:
#    strategy:
#      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 11
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#      - name: Execute Gradle build
#        run: ./gradlew build
#  build-gradle-project:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout project sources
#        uses: actions/checkout@v2
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#      - name: Run build with Gradle Wrapper
#        run: ./gradlew build
#      - name: Run Test
#        run: ./gradlew test
#      - name: Run Coverage
#        run: ./gradlew jacocoTestReport
#      - name: Add coverage to PR
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.3
#        with:
#          paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 40
#          min-coverage-changed-files: 60

name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build