name: Publish package to Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Import signing key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.OSSRH_SIGNING_KEY }}
        run: |
          echo $GPG_PRIVATE_KEY
          echo "$OSSRH_SIGNING_KEY" | gpg --import
      
      - name: Get release version
        id: release
        uses: actions/github-script@v5
        with:
          script: |
            const { data } = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PW: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_PASSPHRASE: ${{ secrets.OSSRH_PASSPHRASE }}
      
      - name: Publish to maven
        run: | 
          ./gradlew "publish -DVERSION=$RELEASE_VERSION"
