name: Publish package to Maven Central Repository
on:
  release:
    types: [created]
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Import signing key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{ secrets.OSSRH_SIGNING_KEY }}
          passphrase: ${{ secrets.OSSRH_PHRASE }}

      - name: List keys
        run: gpg -K

      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v2
      #   env:
      #     OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #     OSSRH_PW: ${{ secrets.OSSRH_TOKEN }}
      #     OSSRH_PASSPHRASE: ${{ secrets.OSSRH_PASSPHRASE }}
      #     RELEASE_VERSION: ${{ github.event.release.tag_name }}
        # id: setup-gradle
        # outputs:
        #   RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - name: Publish to maven
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PW: ${{ secrets.OSSRH_PW }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.OSSRH_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_PASSPHRASE }}
          #          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          RELEASE_VERSION: v0.2.3-rc0
        run: | 
          ./gradlew publish -DVERSION=$RELEASE_VERSION
